export const REFRESH_DATA_PROJECT = "PROJECT/REFRESH_DATA";
export const CLICK_ITEM_PROJECT = "PROJECT/CLICK_ITEM";
export const ASYNC_BEFORE = "ASYNC/BEFORE";
export const ASYNC_SUCCESS = "ASYNC/SUCCESS";
export const ASYNC_FAIL = "ASYNC/FAIL";
